package com.mycompany.prytablas;

import javax.swing.JButton;

/**
 *
 * @author elprofeariel
 */
public class FrmTablaMatriz extends javax.swing.JFrame {
    private ModeloMatriz modelo;    
    public FrmTablaMatriz() {
        initComponents();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarModelo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        cboCuadrado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuadrado Mágico y Modelos de Tabla");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargarModelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargarModelo.setText("Cargar");
        btnCargarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarModeloMouseClicked(evt);
            }
        });
        getContentPane().add(btnCargarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, -1));

        tblMatriz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMatriz);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 340));

        cboCuadrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboCuadrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "5", "7", "9", "11", "13" }));
        getContentPane().add(cboCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarModeloMouseClicked
        int n=Integer.parseInt((String) cboCuadrado.getSelectedItem());
        modelo=new ModeloMatriz(n); 
        tblMatriz.setModel(modelo);
        modelo.cargarMatriz();
    }//GEN-LAST:event_btnCargarModeloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablaMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarModelo;
    private javax.swing.JComboBox<String> cboCuadrado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMatriz;
    // End of variables declaration//GEN-END:variables
}
